export function yonghuziduan (bianma) {
  let allshuju = {
    'Id': 'id',
    'Yonghubianma': '用户编码',
    'Nianling': '年龄',
    'Dizhi': '地址',
    'Xingbie': '性别',
    'Tijian': '体检',
    'Qidong': '启动',
    'Beizhu': '备注',
    'Mingcheng': '名称',
    'Email': '邮箱地址',
    'Shoujihao': '手机号',
    'Riqi': '日期',
    'Shujubianma': '数据编码',
    'Biaoji': '标记',
    'Xueya': '学号',
    'Xuetang': '血糖',
    'Zaoxuetang': '早餐后血糖',
    'Wuxuetang': '午餐后血糖',
    'Wanxuetang': '晚餐后血糖',
    'Ganyousanzhi': '甘油三酯',
    'Gaomiduzhidanbai': '高密度脂蛋白',
    'Tizhong': '体重',
    'Shengao': '身高',
    'Xueniaosuan': '血尿酸',
    'OpenId': 'OpenId',
    'Nickname': '用户昵称',
    'City': '城市',
    'Province': '省份',
    'Country': '国家',
    'HeadImageURL': '头像',
    'Privilege': 'Privilege',
    'UnionId': 'UnionId',
    'Xuliehao': '序列号',
    'Maichu': 'Maichu',
    'Ruwang': 'Ruwang',
    'Yinpinriqi': '音频日期',
    'Tixing': 'Tixing',
    'Macdizhi': 'Macdizhi',
    'Pici': 'Pici',
    'Tianshu': '天数'
  }
  return allshuju[bianma]
}
